### ISSUE TITLE
The explorer is missing an 'about' page

### ISSUE THREAD

**Issue by Ileemans** [Odeuropa/explorer#103]
The Explorer lacks an 'about' page
At this point, I would simply copy paste the information we have on the Odeuropa Website:
https://odeuropa.eu/smell-explorer/

For later I think we need more technical & quantitative data. This can also come in the form of links: to the vocabularies, the benchmark and other data sets, to the notebooks etc. So the Explorer website page becomes the center from which people are propelled to different sites / publications / deliverables.

**Comment by ehrhart** [comment]
I added an About page (source: https://github.com/Odeuropa/explorer/blob/main/src/pages/about.js), which is a simple copy paste of the information from [odeuropa.eu/smell-explorer](https://odeuropa.eu/smell-explorer/). Let me know if there is something to change or feel free to make some changes to the page itself.

**Comment by rtroncy** [comment]
Perfect! Closing for now
