### ISSUE TITLE
Explorer is stalled (no browse pages are loading, no searches are being carried out)

### ISSUE THREAD

**Issue by kintopp** [Odeuropa/explorer#107]
ThE Explorer is not loading at content beyond the home and about pages (none of the browse pages are loading, and no searches are completed). In OSX 14.6.1 with current Safari and Chrome.

**Comment by ehrhart** [comment]
Thanks for reporting this issue. The problem was due to the Redis server being overloaded, but it has been resolved now. Please clear your browser cache and try again. Let us know if you encounter any further issues.
